### ISSUE TITLE
Font size is really big

### ISSUE THREAD

**Issue by Qwe1rty** [Qwe1rty/Event-Planner#10]
I feel like since the font size is really big, there isn't very much that gets displayed at once. Like, if the font and general size of stuff was smaller you'd be able to see more at once and find/adjust things faster. Maybe there could be a setting to adjust it?

I dunno how annoying that would be to implement and change everything though, but just a quaint thought I had

**Comment by sunmatthew** [comment]
i think it's fine right now, the only place where it may be too big is in the table planner, but even then any changes to font size wouldn't make that many more items appear
