### ISSUE TITLE
add to student class

### ISSUE THREAD

**Issue by sunmatthew** [Qwe1rty/Event-Planner#11]
- need to add a boolean guest variable to student constructor (true/false)
- also need a hasGuest method (return true/false if guest/no guest)

**Comment by ConMur** [comment]
Also the search only works for the first if statment. For example when i comment out the student ID search, the first name search works

**Comment by ConMur** [comment]
I fixed the search by adding brackets

**Comment by ConMur** [comment]
sort by table number does not work for some reason

**Comment by sunmatthew** [comment]
it works with my version

**Comment by ConMur** [comment]
im going to work on the student class search
