### ISSUE TITLE
first name sort bugs

### ISSUE THREAD

**Issue by sunmatthew** [Qwe1rty/Event-Planner#13]
Sorting by first name works fine, BUT when adding a new student THEN sorting by first name, the new student is always sorted on top

**Comment by ConMur** [comment]
Is it possible that there is a bug in the sort code?

**Comment by sunmatthew** [comment]
not sure, it's either that or theres a bug when adding a student

**Comment by ConMur** [comment]
i actually have no idea what is happening

**Comment by ConMur** [comment]
im going to work on somethig else if anyone wants to have a look at this

**Comment by Qwe1rty** [comment]
Ive been looking at the sort code but I cant seem to find anything. As long as you recall the sort method after adding the student, it should work 100% in theory

**Comment by sunmatthew** [comment]
if we cant find it don't worry about it
i think  getting the general search to work is more important

**Comment by Qwe1rty** [comment]
So I've played around with the bug a little bit, and it's not a problem with the sort algorithm since it works afterwards. I am pretty confuse atm

**Comment by ConMur** [comment]
got it
