### ISSUE TITLE
Nowhere to load file

### ISSUE THREAD

**Issue by Qwe1rty** [Qwe1rty/Event-Planner#15]
I just realized we don't have a button to load an existing file, eh?

**Comment by ConMur** [comment]
We should add that maybe in settings panel

**Comment by Qwe1rty** [comment]
Yeah the settings panel is probably the best place

**Comment by ConMur** [comment]
Ill add that now

**Comment by ConMur** [comment]
I have the functionality i just need someone who knows how to add the button to the panel
