### ISSUE TITLE
Regarding commit 66f200225ade8ab61ea41f3f2a5d8b2216ceb044

### ISSUE THREAD

**Issue by Qwe1rty** [Qwe1rty/Event-Planner#18]
Connor, did you make any changes to the saveAsFile() and saveFile() methods? I've made some changes and have to resolve the merge conflict, and the commit log is not being very useful

**Comment by ConMur** [comment]
yes

**Comment by ConMur** [comment]
but i did that a while ago so im not sure if that is me. I have been working on the loader file though and it seems that we are doing the same thing so ill just use your version

**Comment by Qwe1rty** [comment]
I've merged the parseFile() methods, but I've completely overridden your save methods because I wasn't able to find any changes that you made. So if you made any changes to them, you should probably manually add them back

**Comment by ConMur** [comment]
looks good to me
