### ISSUE TITLE
Cannot save a file when the user did not initially select a file

### ISSUE THREAD

**Issue by ConMur** [Qwe1rty/Event-Planner#5]

**Comment by Qwe1rty** [comment]
Did you pull the latest vers.? There should be two methods: one for "saving as" and one for just "save". If you're saving a file for the first time, you have to call save as

**Comment by ConMur** [comment]
Whoops

**Comment by ConMur** [comment]
How am i supposed to know if the file is valid?

**Comment by Qwe1rty** [comment]
I believe if it's messed up/corrupted it should fail somewhere in the file parsing and throw an exception of some sort. I have no real idea, though and there isn't a great way to check

**Comment by ConMur** [comment]
Can i modify the loader class to do the checking for me or are you working on it?

**Comment by Qwe1rty** [comment]
i guess you can do it, but how exactly is it going to be implemented?

**Comment by ConMur** [comment]
basically if currentFile == null use save as if not use save

**Comment by Qwe1rty** [comment]
oh okay cool, go right ahead
