### ISSUE TITLE
Student class

### ISSUE THREAD

**Issue by sunmatthew** [Qwe1rty/Event-Planner#8]
need to make initials a mandatory field and a setInitials() method

**Comment by Qwe1rty** [comment]
Initials implemented! Tell me if you come across any issues

**Comment by sunmatthew** [comment]
guests need to have a student ID

**Comment by Qwe1rty** [comment]
im pretty sure they dont, since guests don't even have one. If it's a guest, you should set it to 9 zero's

**Comment by sunmatthew** [comment]
what i thought guests have the same ID as the person who is bringing the guest

**Comment by Qwe1rty** [comment]
Huh, I dunno then. Connor should probably know
CONNOR HALP

**Comment by sunmatthew** [comment]
ok just confirmed w/ connor, guest ID is mandatory

**Comment by Qwe1rty** [comment]
aw bollocks.ill get rid of the guest constructor, then

**Comment by Qwe1rty** [comment]
Okay, guest stuff is gone now

**Comment by ConMur** [comment]
I thought you meant that the initials were needed (which they are) the 000000000 thing for guests works well

**Comment by ConMur** [comment]
its late i cant read

**Comment by Qwe1rty** [comment]
Ack! Well, I've just readded them then
